addition_task:
  batch_size: 64
  data_dir: data/Adding_task/data100
  input_size: 2
  model_dir: addition_task_weights/final.pt
  output_size: 1
  save_dir: weights/addition_task_weights
  test_num: 1000
  train_num: 10000
device: cuda
epoch: 10
eval: true
hidden_size: 10
k1: 2
k2: 3
r: 0.01
task_name: addition_task
train_from_scratch: true
