addition_task:
  batch_size: 256
  data_dir: data/adding_task/data/data10
  input_size: 2
  model_dir: weights/addition_task_weights/data10/final.pt
  output_size: 1
  save_dir: weights/addition_task_weights/data30
  test_num: 1000
  train_num: 50000
copy_task:
  batch_size: 256
  data_dir: data/copy_task/data/data30
  input_size: 10
  model_dir: weights/copy_task_weights/data30/final.pt
  output_size: 10
  save_dir: weights/copy_task_weights/data30
  test_num: 1000
  train_num: 50000
device: cuda
epoch: 1000
eval_only: false
hidden_size: 128
k1: 1
k2: 1
lr: 0.01
r: 0.01
#task_name: addition_task
task_name: copy_task
train_from_scratch: true
